development:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  spotify_client_id: <%= ENV["SPOTIFY_CLIENT_ID"] %>
  spotify_api_key: <%= ENV["SPOTIFY_API_KEY"] %>
test:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  spotify_client_id: <%= ENV["SPOTIFY_CLIENT_ID"] %>
  spotify_api_key: <%= ENV["SPOTIFY_API_KEY"] %>
production:
  cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
  spotify_client_id: <%= ENV["SPOTIFY_CLIENT_ID"] %>
  spotify_api_key: <%= ENV["SPOTIFY_API_KEY"] %>